-- ============================================================
-- M068: Rebuild Turkish TDHP chart_of_accounts for PARK GROUP
-- ============================================================
-- PARK GROUP'un önceki yüklemeleri (karışık ülke şablonu denemeleri) sildi
-- ve resmi Türkiye Tekdüzen Hesap Planı'nı yeniden seed eder.
-- 211 hesap — sadece company_id=PARK, diğer şirketler etkilenmez.
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_company_id uuid;
  v_count int;
BEGIN
  SELECT id INTO v_company_id FROM companies WHERE name ILIKE '%PARK%' AND deleted_at IS NULL LIMIT 1;
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'PARK company not found';
  END IF;

  -- Wipe existing chart_of_accounts for this company (safe: no journal_entries
  -- or non-zero balances reference them — verified before migration).
  DELETE FROM chart_of_accounts WHERE company_id = v_company_id;

  -- Insert full Turkish TDHP
  INSERT INTO chart_of_accounts (company_id, code, name, name_local, type, level, parent_code, country_code, is_system, is_active) VALUES
  (v_company_id, '1', 'Dönen Varlıklar', 'Dönen Varlıklar', 'asset', 1, NULL, 'TR', false, true),
  (v_company_id, '10', 'Hazır Değerler', 'Hazır Değerler', 'asset', 2, '1', 'TR', false, true),
  (v_company_id, '100', 'Kasa', 'Kasa', 'asset', 3, '10', 'TR', false, true),
  (v_company_id, '101', 'Alınan Çekler', 'Alınan Çekler', 'asset', 3, '10', 'TR', false, true),
  (v_company_id, '102', 'Bankalar', 'Bankalar', 'asset', 3, '10', 'TR', false, true),
  (v_company_id, '103', 'Verilen Çekler ve Ödeme Emirleri (-)', 'Verilen Çekler ve Ödeme Emirleri (-)', 'asset', 3, '10', 'TR', false, true),
  (v_company_id, '108', 'Diğer Hazır Değerler', 'Diğer Hazır Değerler', 'asset', 3, '10', 'TR', false, true),
  (v_company_id, '12', 'Ticari Alacaklar', 'Ticari Alacaklar', 'asset', 2, '1', 'TR', false, true),
  (v_company_id, '120', 'Alıcılar', 'Alıcılar', 'asset', 3, '12', 'TR', false, true),
  (v_company_id, '121', 'Alacak Senetleri', 'Alacak Senetleri', 'asset', 3, '12', 'TR', false, true),
  (v_company_id, '127', 'Diğer Ticari Alacaklar', 'Diğer Ticari Alacaklar', 'asset', 3, '12', 'TR', false, true),
  (v_company_id, '128', 'Şüpheli Ticari Alacaklar', 'Şüpheli Ticari Alacaklar', 'asset', 3, '12', 'TR', false, true),
  (v_company_id, '129', 'Şüpheli Alacaklar Karşılığı (-)', 'Şüpheli Alacaklar Karşılığı (-)', 'asset', 3, '12', 'TR', false, true),
  (v_company_id, '13', 'Diğer Alacaklar', 'Diğer Alacaklar', 'asset', 2, '1', 'TR', false, true),
  (v_company_id, '131', 'Ortaklardan Alacaklar', 'Ortaklardan Alacaklar', 'asset', 3, '13', 'TR', false, true),
  (v_company_id, '132', 'İştiraklerden Alacaklar', 'İştiraklerden Alacaklar', 'asset', 3, '13', 'TR', false, true),
  (v_company_id, '133', 'Bağlı Ortaklıklardan Alacaklar', 'Bağlı Ortaklıklardan Alacaklar', 'asset', 3, '13', 'TR', false, true),
  (v_company_id, '135', 'Personelden Alacaklar', 'Personelden Alacaklar', 'asset', 3, '13', 'TR', false, true),
  (v_company_id, '136', 'Diğer Çeşitli Alacaklar', 'Diğer Çeşitli Alacaklar', 'asset', 3, '13', 'TR', false, true),
  (v_company_id, '15', 'Stoklar', 'Stoklar', 'asset', 2, '1', 'TR', false, true),
  (v_company_id, '150', 'İlk Madde ve Malzeme', 'İlk Madde ve Malzeme', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '151', 'Yarı Mamuller', 'Yarı Mamuller', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '152', 'Mamuller', 'Mamuller', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '153', 'Ticari Mallar', 'Ticari Mallar', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '157', 'Diğer Stoklar', 'Diğer Stoklar', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '158', 'Stok Değer Düşüklüğü Karşılığı (-)', 'Stok Değer Düşüklüğü Karşılığı (-)', 'asset', 3, '15', 'TR', false, true),
  (v_company_id, '19', 'Diğer Dönen Varlıklar', 'Diğer Dönen Varlıklar', 'asset', 2, '1', 'TR', false, true),
  (v_company_id, '190', 'Devreden KDV', 'Devreden KDV', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '191', 'İndirilecek KDV', 'İndirilecek KDV', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '192', 'Diğer KDV', 'Diğer KDV', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '195', 'İş Avansları', 'İş Avansları', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '196', 'Personel Avansları', 'Personel Avansları', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '197', 'Sayım ve Tesellüm Noksanları', 'Sayım ve Tesellüm Noksanları', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '199', 'Diğer Çeşitli Dönen Varlıklar', 'Diğer Çeşitli Dönen Varlıklar', 'asset', 3, '19', 'TR', false, true),
  (v_company_id, '2', 'Duran Varlıklar', 'Duran Varlıklar', 'asset', 1, NULL, 'TR', false, true),
  (v_company_id, '22', 'Ticari Alacaklar', 'Ticari Alacaklar', 'asset', 2, '2', 'TR', false, true),
  (v_company_id, '220', 'Alıcılar', 'Alıcılar', 'asset', 3, '22', 'TR', false, true),
  (v_company_id, '221', 'Alacak Senetleri', 'Alacak Senetleri', 'asset', 3, '22', 'TR', false, true),
  (v_company_id, '25', 'Maddi Duran Varlıklar', 'Maddi Duran Varlıklar', 'asset', 2, '2', 'TR', false, true),
  (v_company_id, '250', 'Arazi ve Arsalar', 'Arazi ve Arsalar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '251', 'Yeraltı ve Yerüstü Düzenleri', 'Yeraltı ve Yerüstü Düzenleri', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '252', 'Binalar', 'Binalar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '253', 'Tesis, Makine ve Cihazlar', 'Tesis, Makine ve Cihazlar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '254', 'Taşıtlar', 'Taşıtlar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '255', 'Demirbaşlar', 'Demirbaşlar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '256', 'Diğer Maddi Duran Varlıklar', 'Diğer Maddi Duran Varlıklar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '257', 'Birikmiş Amortismanlar (-)', 'Birikmiş Amortismanlar (-)', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '258', 'Yapılmakta Olan Yatırımlar', 'Yapılmakta Olan Yatırımlar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '259', 'Verilen Avanslar', 'Verilen Avanslar', 'asset', 3, '25', 'TR', false, true),
  (v_company_id, '26', 'Maddi Olmayan Duran Varlıklar', 'Maddi Olmayan Duran Varlıklar', 'asset', 2, '2', 'TR', false, true),
  (v_company_id, '260', 'Haklar', 'Haklar', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '261', 'Şerefiye', 'Şerefiye', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '262', 'Kuruluş ve Örgütlenme Giderleri', 'Kuruluş ve Örgütlenme Giderleri', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '263', 'Araştırma ve Geliştirme Giderleri', 'Araştırma ve Geliştirme Giderleri', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '264', 'Özel Maliyetler', 'Özel Maliyetler', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '267', 'Diğer Maddi Olmayan Duran Varlıklar', 'Diğer Maddi Olmayan Duran Varlıklar', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '268', 'Birikmiş Amortismanlar (-)', 'Birikmiş Amortismanlar (-)', 'asset', 3, '26', 'TR', false, true),
  (v_company_id, '3', 'Kısa Vadeli Yabancı Kaynaklar', 'Kısa Vadeli Yabancı Kaynaklar', 'liability', 1, NULL, 'TR', false, true),
  (v_company_id, '30', 'Mali Borçlar', 'Mali Borçlar', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '300', 'Banka Kredileri', 'Banka Kredileri', 'liability', 3, '30', 'TR', false, true),
  (v_company_id, '303', 'Uzun Vadeli Kredilerin Anapara Taksitleri', 'Uzun Vadeli Kredilerin Anapara Taksitleri', 'liability', 3, '30', 'TR', false, true),
  (v_company_id, '304', 'Tahvil Anapara Borç Taksit ve Faizleri', 'Tahvil Anapara Borç Taksit ve Faizleri', 'liability', 3, '30', 'TR', false, true),
  (v_company_id, '308', 'Menkul Kıymetler İhraç Farkı', 'Menkul Kıymetler İhraç Farkı', 'liability', 3, '30', 'TR', false, true),
  (v_company_id, '32', 'Ticari Borçlar', 'Ticari Borçlar', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '320', 'Satıcılar', 'Satıcılar', 'liability', 3, '32', 'TR', false, true),
  (v_company_id, '321', 'Borç Senetleri', 'Borç Senetleri', 'liability', 3, '32', 'TR', false, true),
  (v_company_id, '322', 'Borç Senetleri Reeskontu (-)', 'Borç Senetleri Reeskontu (-)', 'liability', 3, '32', 'TR', false, true),
  (v_company_id, '326', 'Alınan Depozito ve Teminatlar', 'Alınan Depozito ve Teminatlar', 'liability', 3, '32', 'TR', false, true),
  (v_company_id, '329', 'Diğer Ticari Borçlar', 'Diğer Ticari Borçlar', 'liability', 3, '32', 'TR', false, true),
  (v_company_id, '33', 'Diğer Borçlar', 'Diğer Borçlar', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '331', 'Ortaklara Borçlar', 'Ortaklara Borçlar', 'liability', 3, '33', 'TR', false, true),
  (v_company_id, '332', 'İştiraklere Borçlar', 'İştiraklere Borçlar', 'liability', 3, '33', 'TR', false, true),
  (v_company_id, '333', 'Bağlı Ortaklıklara Borçlar', 'Bağlı Ortaklıklara Borçlar', 'liability', 3, '33', 'TR', false, true),
  (v_company_id, '335', 'Personele Borçlar', 'Personele Borçlar', 'liability', 3, '33', 'TR', false, true),
  (v_company_id, '336', 'Diğer Çeşitli Borçlar', 'Diğer Çeşitli Borçlar', 'liability', 3, '33', 'TR', false, true),
  (v_company_id, '34', 'Alınan Avanslar', 'Alınan Avanslar', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '340', 'Alınan Sipariş Avansları', 'Alınan Sipariş Avansları', 'liability', 3, '34', 'TR', false, true),
  (v_company_id, '349', 'Alınan Diğer Avanslar', 'Alınan Diğer Avanslar', 'liability', 3, '34', 'TR', false, true),
  (v_company_id, '36', 'Ödenecek Vergi ve Diğer Yükümlülükler', 'Ödenecek Vergi ve Diğer Yükümlülükler', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '360', 'Ödenecek Vergi ve Fonlar', 'Ödenecek Vergi ve Fonlar', 'liability', 3, '36', 'TR', false, true),
  (v_company_id, '361', 'Ödenecek Sosyal Güvenlik Kesintileri', 'Ödenecek Sosyal Güvenlik Kesintileri', 'liability', 3, '36', 'TR', false, true),
  (v_company_id, '368', 'Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler', 'Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler', 'liability', 3, '36', 'TR', false, true),
  (v_company_id, '369', 'Ödenecek Diğer Yükümlülükler', 'Ödenecek Diğer Yükümlülükler', 'liability', 3, '36', 'TR', false, true),
  (v_company_id, '37', 'Borç ve Gider Karşılıkları', 'Borç ve Gider Karşılıkları', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '370', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', 'liability', 3, '37', 'TR', false, true),
  (v_company_id, '371', 'Dönem Kârının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', 'Dönem Kârının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', 'liability', 3, '37', 'TR', false, true),
  (v_company_id, '372', 'Kıdem Tazminatı Karşılığı', 'Kıdem Tazminatı Karşılığı', 'liability', 3, '37', 'TR', false, true),
  (v_company_id, '373', 'Maliyet Giderleri Karşılığı', 'Maliyet Giderleri Karşılığı', 'liability', 3, '37', 'TR', false, true),
  (v_company_id, '39', 'Diğer Kısa Vadeli Yabancı Kaynaklar', 'Diğer Kısa Vadeli Yabancı Kaynaklar', 'liability', 2, '3', 'TR', false, true),
  (v_company_id, '391', 'Hesaplanan KDV', 'Hesaplanan KDV', 'liability', 3, '39', 'TR', false, true),
  (v_company_id, '392', 'Diğer KDV', 'Diğer KDV', 'liability', 3, '39', 'TR', false, true),
  (v_company_id, '395', 'Merkez ve Şubeler Cari Hesabı', 'Merkez ve Şubeler Cari Hesabı', 'liability', 3, '39', 'TR', false, true),
  (v_company_id, '397', 'Sayım ve Tesellüm Fazlaları', 'Sayım ve Tesellüm Fazlaları', 'liability', 3, '39', 'TR', false, true),
  (v_company_id, '399', 'Diğer Çeşitli Yabancı Kaynaklar', 'Diğer Çeşitli Yabancı Kaynaklar', 'liability', 3, '39', 'TR', false, true),
  (v_company_id, '4', 'Uzun Vadeli Yabancı Kaynaklar', 'Uzun Vadeli Yabancı Kaynaklar', 'liability', 1, NULL, 'TR', false, true),
  (v_company_id, '40', 'Mali Borçlar', 'Mali Borçlar', 'liability', 2, '4', 'TR', false, true),
  (v_company_id, '400', 'Banka Kredileri', 'Banka Kredileri', 'liability', 3, '40', 'TR', false, true),
  (v_company_id, '405', 'Çıkarılmış Tahviller', 'Çıkarılmış Tahviller', 'liability', 3, '40', 'TR', false, true),
  (v_company_id, '407', 'Çıkarılmış Diğer Menkul Kıymetler', 'Çıkarılmış Diğer Menkul Kıymetler', 'liability', 3, '40', 'TR', false, true),
  (v_company_id, '408', 'Menkul Kıymetler İhraç Farkı (-)', 'Menkul Kıymetler İhraç Farkı (-)', 'liability', 3, '40', 'TR', false, true),
  (v_company_id, '409', 'Diğer Mali Borçlar', 'Diğer Mali Borçlar', 'liability', 3, '40', 'TR', false, true),
  (v_company_id, '42', 'Ticari Borçlar', 'Ticari Borçlar', 'liability', 2, '4', 'TR', false, true),
  (v_company_id, '420', 'Satıcılar', 'Satıcılar', 'liability', 3, '42', 'TR', false, true),
  (v_company_id, '421', 'Borç Senetleri', 'Borç Senetleri', 'liability', 3, '42', 'TR', false, true),
  (v_company_id, '426', 'Alınan Depozito ve Teminatlar', 'Alınan Depozito ve Teminatlar', 'liability', 3, '42', 'TR', false, true),
  (v_company_id, '429', 'Diğer Ticari Borçlar', 'Diğer Ticari Borçlar', 'liability', 3, '42', 'TR', false, true),
  (v_company_id, '5', 'Öz Kaynaklar', 'Öz Kaynaklar', 'equity', 1, NULL, 'TR', false, true),
  (v_company_id, '50', 'Ödenmiş Sermaye', 'Ödenmiş Sermaye', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '500', 'Sermaye', 'Sermaye', 'equity', 3, '50', 'TR', false, true),
  (v_company_id, '501', 'Ödenmemiş Sermaye (-)', 'Ödenmemiş Sermaye (-)', 'equity', 3, '50', 'TR', false, true),
  (v_company_id, '52', 'Sermaye Yedekleri', 'Sermaye Yedekleri', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '520', 'Hisse Senedi İhraç Primleri', 'Hisse Senedi İhraç Primleri', 'equity', 3, '52', 'TR', false, true),
  (v_company_id, '521', 'Hisse Senedi İptal Kârları', 'Hisse Senedi İptal Kârları', 'equity', 3, '52', 'TR', false, true),
  (v_company_id, '522', 'M.D.V. Yeniden Değerleme Artışları', 'M.D.V. Yeniden Değerleme Artışları', 'equity', 3, '52', 'TR', false, true),
  (v_company_id, '54', 'Kâr Yedekleri', 'Kâr Yedekleri', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '540', 'Yasal Yedekler', 'Yasal Yedekler', 'equity', 3, '54', 'TR', false, true),
  (v_company_id, '541', 'Statü Yedekleri', 'Statü Yedekleri', 'equity', 3, '54', 'TR', false, true),
  (v_company_id, '542', 'Olağanüstü Yedekler', 'Olağanüstü Yedekler', 'equity', 3, '54', 'TR', false, true),
  (v_company_id, '57', 'Geçmiş Yıllar Kârları', 'Geçmiş Yıllar Kârları', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '570', 'Geçmiş Yıllar Kârları', 'Geçmiş Yıllar Kârları', 'equity', 3, '57', 'TR', false, true),
  (v_company_id, '58', 'Geçmiş Yıllar Zararları', 'Geçmiş Yıllar Zararları', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '580', 'Geçmiş Yıllar Zararları (-)', 'Geçmiş Yıllar Zararları (-)', 'equity', 3, '58', 'TR', false, true),
  (v_company_id, '59', 'Dönem Net Kârı (Zararı)', 'Dönem Net Kârı (Zararı)', 'equity', 2, '5', 'TR', false, true),
  (v_company_id, '590', 'Dönem Net Kârı', 'Dönem Net Kârı', 'equity', 3, '59', 'TR', false, true),
  (v_company_id, '591', 'Dönem Net Zararı (-)', 'Dönem Net Zararı (-)', 'equity', 3, '59', 'TR', false, true),
  (v_company_id, '6', 'Gelir Tablosu Hesapları', 'Gelir Tablosu Hesapları', 'revenue', 1, NULL, 'TR', false, true),
  (v_company_id, '60', 'Brüt Satışlar', 'Brüt Satışlar', 'revenue', 2, '6', 'TR', false, true),
  (v_company_id, '600', 'Yurtiçi Satışlar', 'Yurtiçi Satışlar', 'revenue', 3, '60', 'TR', false, true),
  (v_company_id, '601', 'Yurtdışı Satışlar', 'Yurtdışı Satışlar', 'revenue', 3, '60', 'TR', false, true),
  (v_company_id, '602', 'Diğer Gelirler', 'Diğer Gelirler', 'revenue', 3, '60', 'TR', false, true),
  (v_company_id, '61', 'Satış İndirimleri', 'Satış İndirimleri', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '610', 'Satıştan İadeler (-)', 'Satıştan İadeler (-)', 'expense', 3, '61', 'TR', false, true),
  (v_company_id, '611', 'Satış İskontoları (-)', 'Satış İskontoları (-)', 'expense', 3, '61', 'TR', false, true),
  (v_company_id, '612', 'Diğer İndirimler (-)', 'Diğer İndirimler (-)', 'expense', 3, '61', 'TR', false, true),
  (v_company_id, '62', 'Satışların Maliyeti', 'Satışların Maliyeti', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '620', 'Satılan Mamuller Maliyeti (-)', 'Satılan Mamuller Maliyeti (-)', 'expense', 3, '62', 'TR', false, true),
  (v_company_id, '621', 'Satılan Ticari Mallar Maliyeti (-)', 'Satılan Ticari Mallar Maliyeti (-)', 'expense', 3, '62', 'TR', false, true),
  (v_company_id, '622', 'Satılan Hizmet Maliyeti (-)', 'Satılan Hizmet Maliyeti (-)', 'expense', 3, '62', 'TR', false, true),
  (v_company_id, '623', 'Diğer Satışların Maliyeti (-)', 'Diğer Satışların Maliyeti (-)', 'expense', 3, '62', 'TR', false, true),
  (v_company_id, '63', 'Faaliyet Giderleri', 'Faaliyet Giderleri', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '630', 'Araştırma ve Geliştirme Giderleri (-)', 'Araştırma ve Geliştirme Giderleri (-)', 'expense', 3, '63', 'TR', false, true),
  (v_company_id, '631', 'Pazarlama, Satış ve Dağıtım Giderleri (-)', 'Pazarlama, Satış ve Dağıtım Giderleri (-)', 'expense', 3, '63', 'TR', false, true),
  (v_company_id, '632', 'Genel Yönetim Giderleri (-)', 'Genel Yönetim Giderleri (-)', 'expense', 3, '63', 'TR', false, true),
  (v_company_id, '64', 'Diğer Faaliyetlerden Olağan Gelir ve Kârlar', 'Diğer Faaliyetlerden Olağan Gelir ve Kârlar', 'revenue', 2, '6', 'TR', false, true),
  (v_company_id, '640', 'İştiraklerden Temettü Gelirleri', 'İştiraklerden Temettü Gelirleri', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '641', 'Bağlı Ortaklıklardan Temettü Gelirleri', 'Bağlı Ortaklıklardan Temettü Gelirleri', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '642', 'Faiz Gelirleri', 'Faiz Gelirleri', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '643', 'Komisyon Gelirleri', 'Komisyon Gelirleri', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '644', 'Konusu Kalmayan Karşılıklar', 'Konusu Kalmayan Karşılıklar', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '645', 'Menkul Kıymet Satış Kârları', 'Menkul Kıymet Satış Kârları', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '646', 'Kambiyo Kârları', 'Kambiyo Kârları', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '647', 'Reeskont Faiz Gelirleri', 'Reeskont Faiz Gelirleri', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '649', 'Diğer Olağan Gelir ve Kârlar', 'Diğer Olağan Gelir ve Kârlar', 'revenue', 3, '64', 'TR', false, true),
  (v_company_id, '65', 'Diğer Faaliyetlerden Olağan Gider ve Zararlar', 'Diğer Faaliyetlerden Olağan Gider ve Zararlar', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '653', 'Komisyon Giderleri (-)', 'Komisyon Giderleri (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '654', 'Karşılık Giderleri (-)', 'Karşılık Giderleri (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '655', 'Menkul Kıymet Satış Zararları (-)', 'Menkul Kıymet Satış Zararları (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '656', 'Kambiyo Zararları (-)', 'Kambiyo Zararları (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '657', 'Reeskont Faiz Giderleri (-)', 'Reeskont Faiz Giderleri (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '659', 'Diğer Olağan Gider ve Zararlar (-)', 'Diğer Olağan Gider ve Zararlar (-)', 'expense', 3, '65', 'TR', false, true),
  (v_company_id, '66', 'Finansman Giderleri', 'Finansman Giderleri', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '660', 'Kısa Vadeli Borçlanma Giderleri (-)', 'Kısa Vadeli Borçlanma Giderleri (-)', 'expense', 3, '66', 'TR', false, true),
  (v_company_id, '661', 'Uzun Vadeli Borçlanma Giderleri (-)', 'Uzun Vadeli Borçlanma Giderleri (-)', 'expense', 3, '66', 'TR', false, true),
  (v_company_id, '67', 'Olağandışı Gelir ve Kârlar', 'Olağandışı Gelir ve Kârlar', 'revenue', 2, '6', 'TR', false, true),
  (v_company_id, '671', 'Önceki Dönem Gelir ve Kârları', 'Önceki Dönem Gelir ve Kârları', 'revenue', 3, '67', 'TR', false, true),
  (v_company_id, '679', 'Diğer Olağandışı Gelir ve Kârlar', 'Diğer Olağandışı Gelir ve Kârlar', 'revenue', 3, '67', 'TR', false, true),
  (v_company_id, '68', 'Olağandışı Gider ve Zararlar', 'Olağandışı Gider ve Zararlar', 'expense', 2, '6', 'TR', false, true),
  (v_company_id, '680', 'Çalışmayan Kısım Gider ve Zararları (-)', 'Çalışmayan Kısım Gider ve Zararları (-)', 'expense', 3, '68', 'TR', false, true),
  (v_company_id, '681', 'Önceki Dönem Gider ve Zararları (-)', 'Önceki Dönem Gider ve Zararları (-)', 'expense', 3, '68', 'TR', false, true),
  (v_company_id, '689', 'Diğer Olağandışı Gider ve Zararlar (-)', 'Diğer Olağandışı Gider ve Zararlar (-)', 'expense', 3, '68', 'TR', false, true),
  (v_company_id, '69', 'Dönem Net Kâr veya Zararı', 'Dönem Net Kâr veya Zararı', 'equity', 2, '6', 'TR', false, true),
  (v_company_id, '690', 'Dönem Kârı veya Zararı', 'Dönem Kârı veya Zararı', 'equity', 3, '69', 'TR', false, true),
  (v_company_id, '691', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', 'equity', 3, '69', 'TR', false, true),
  (v_company_id, '692', 'Dönem Net Kârı veya Zararı', 'Dönem Net Kârı veya Zararı', 'equity', 3, '69', 'TR', false, true),
  (v_company_id, '7', 'Maliyet Hesapları', 'Maliyet Hesapları', 'cost', 1, NULL, 'TR', false, true),
  (v_company_id, '71', 'Direkt İlk Madde ve Malzeme Giderleri', 'Direkt İlk Madde ve Malzeme Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '710', 'Direkt İlk Madde ve Malzeme Giderleri', 'Direkt İlk Madde ve Malzeme Giderleri', 'cost', 3, '71', 'TR', false, true),
  (v_company_id, '711', 'Direkt İlk Madde ve Malzeme Yansıtma Hesabı', 'Direkt İlk Madde ve Malzeme Yansıtma Hesabı', 'cost', 3, '71', 'TR', false, true),
  (v_company_id, '712', 'Direkt İlk Madde ve Malzeme Fiyat Farkı', 'Direkt İlk Madde ve Malzeme Fiyat Farkı', 'cost', 3, '71', 'TR', false, true),
  (v_company_id, '713', 'Direkt İlk Madde ve Malzeme Miktar Farkı', 'Direkt İlk Madde ve Malzeme Miktar Farkı', 'cost', 3, '71', 'TR', false, true),
  (v_company_id, '72', 'Direkt İşçilik Giderleri', 'Direkt İşçilik Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '720', 'Direkt İşçilik Giderleri', 'Direkt İşçilik Giderleri', 'cost', 3, '72', 'TR', false, true),
  (v_company_id, '721', 'Direkt İşçilik Giderleri Yansıtma Hesabı', 'Direkt İşçilik Giderleri Yansıtma Hesabı', 'cost', 3, '72', 'TR', false, true),
  (v_company_id, '722', 'Direkt İşçilik Ücret Farkları', 'Direkt İşçilik Ücret Farkları', 'cost', 3, '72', 'TR', false, true),
  (v_company_id, '723', 'Direkt İşçilik Süre (Zaman) Farkları', 'Direkt İşçilik Süre (Zaman) Farkları', 'cost', 3, '72', 'TR', false, true),
  (v_company_id, '73', 'Genel Üretim Giderleri', 'Genel Üretim Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '730', 'Genel Üretim Giderleri', 'Genel Üretim Giderleri', 'cost', 3, '73', 'TR', false, true),
  (v_company_id, '731', 'Genel Üretim Giderleri Yansıtma Hesabı', 'Genel Üretim Giderleri Yansıtma Hesabı', 'cost', 3, '73', 'TR', false, true),
  (v_company_id, '732', 'Genel Üretim Giderleri Bütçe Farkları', 'Genel Üretim Giderleri Bütçe Farkları', 'cost', 3, '73', 'TR', false, true),
  (v_company_id, '733', 'Genel Üretim Giderleri Verimlilik Farkları', 'Genel Üretim Giderleri Verimlilik Farkları', 'cost', 3, '73', 'TR', false, true),
  (v_company_id, '734', 'Genel Üretim Giderleri Kapasite Farkları', 'Genel Üretim Giderleri Kapasite Farkları', 'cost', 3, '73', 'TR', false, true),
  (v_company_id, '74', 'Hizmet Üretim Maliyeti', 'Hizmet Üretim Maliyeti', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '740', 'Hizmet Üretim Maliyeti', 'Hizmet Üretim Maliyeti', 'cost', 3, '74', 'TR', false, true),
  (v_company_id, '741', 'Hizmet Üretim Maliyeti Yansıtma Hesabı', 'Hizmet Üretim Maliyeti Yansıtma Hesabı', 'cost', 3, '74', 'TR', false, true),
  (v_company_id, '742', 'Hizmet Üretim Maliyeti Fark Hesapları', 'Hizmet Üretim Maliyeti Fark Hesapları', 'cost', 3, '74', 'TR', false, true),
  (v_company_id, '75', 'Araştırma ve Geliştirme Giderleri', 'Araştırma ve Geliştirme Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '750', 'Araştırma ve Geliştirme Giderleri', 'Araştırma ve Geliştirme Giderleri', 'cost', 3, '75', 'TR', false, true),
  (v_company_id, '751', 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı', 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı', 'cost', 3, '75', 'TR', false, true),
  (v_company_id, '752', 'Araştırma ve Geliştirme Gider Farkları', 'Araştırma ve Geliştirme Gider Farkları', 'cost', 3, '75', 'TR', false, true),
  (v_company_id, '76', 'Pazarlama Satış ve Dağıtım Giderleri', 'Pazarlama Satış ve Dağıtım Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '760', 'Pazarlama Satış ve Dağıtım Giderleri', 'Pazarlama Satış ve Dağıtım Giderleri', 'cost', 3, '76', 'TR', false, true),
  (v_company_id, '761', 'Pazarlama Satış ve Dağıtım Giderleri Yansıtma Hesabı', 'Pazarlama Satış ve Dağıtım Giderleri Yansıtma Hesabı', 'cost', 3, '76', 'TR', false, true),
  (v_company_id, '762', 'Pazarlama Satış ve Dağıtım Giderleri Fark Hesabı', 'Pazarlama Satış ve Dağıtım Giderleri Fark Hesabı', 'cost', 3, '76', 'TR', false, true),
  (v_company_id, '77', 'Genel Yönetim Giderleri', 'Genel Yönetim Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '770', 'Genel Yönetim Giderleri', 'Genel Yönetim Giderleri', 'cost', 3, '77', 'TR', false, true),
  (v_company_id, '771', 'Genel Yönetim Giderleri Yansıtma Hesabı', 'Genel Yönetim Giderleri Yansıtma Hesabı', 'cost', 3, '77', 'TR', false, true),
  (v_company_id, '772', 'Genel Yönetim Gider Farkları', 'Genel Yönetim Gider Farkları', 'cost', 3, '77', 'TR', false, true),
  (v_company_id, '78', 'Finansman Giderleri', 'Finansman Giderleri', 'cost', 2, '7', 'TR', false, true),
  (v_company_id, '780', 'Finansman Giderleri', 'Finansman Giderleri', 'cost', 3, '78', 'TR', false, true),
  (v_company_id, '781', 'Finansman Giderleri Yansıtma Hesabı', 'Finansman Giderleri Yansıtma Hesabı', 'cost', 3, '78', 'TR', false, true),
  (v_company_id, '782', 'Finansman Giderleri Fark Hesabı', 'Finansman Giderleri Fark Hesabı', 'cost', 3, '78', 'TR', false, true);

  -- Resolve parent_id from parent_code within the same company.
  UPDATE chart_of_accounts c
  SET parent_id = p.id
  FROM chart_of_accounts p
  WHERE c.company_id = v_company_id
    AND p.company_id = v_company_id
    AND c.parent_code = p.code
    AND c.parent_id IS NULL;

  SELECT COUNT(*) INTO v_count FROM chart_of_accounts WHERE company_id = v_company_id;
  RAISE NOTICE 'PARK GROUP chart_of_accounts rebuilt: % rows', v_count;
END $$;

INSERT INTO migrations_log (file_name, notes)
VALUES ('068_turkey_coa_parkgroup_rebuild.sql',
  'PARK GROUP: Türkiye TDHP 211 hesap (resmi kodlar) — şablon sorunlu olduğu için tek şirkete özel rebuild.')
ON CONFLICT (file_name) DO NOTHING;

COMMIT;
