-- ============================================================
-- M069: Rebuild TR template in chart_of_accounts_templates
-- ============================================================
-- Şimdiye dek TR şablonu resmi TDHP ile uyumlu değildi. Yeni şirket
-- kurulduğunda veya Ayarlar > Muhasebe > Şablon Yükle akışı
-- (accounting.html:731) çağrıldığında buradan kopyalandığı için hatalı
-- veri yeniden üretiliyordu. 211 resmi TDHP hesabıyla değiştiriyor.
-- Başka ülke şablonları etkilenmez.
-- ============================================================

BEGIN;

DELETE FROM chart_of_accounts_templates WHERE country_code = 'TR';

INSERT INTO chart_of_accounts_templates
  (country_code, account_code, account_name_local, account_name_en, account_type, parent_code, level, is_mandatory)
VALUES
  ('TR', '1', 'Dönen Varlıklar', 'Current Assets', 'asset', NULL, 1, true),
  ('TR', '10', 'Hazır Değerler', 'Cash and Cash Equivalents', 'asset', '1', 2, true),
  ('TR', '100', 'Kasa', 'Cash on Hand', 'asset', '10', 3, true),
  ('TR', '101', 'Alınan Çekler', 'Cheques Received', 'asset', '10', 3, true),
  ('TR', '102', 'Bankalar', 'Banks', 'asset', '10', 3, true),
  ('TR', '103', 'Verilen Çekler ve Ödeme Emirleri (-)', 'Cheques Given and Payment Orders (-)', 'asset', '10', 3, true),
  ('TR', '108', 'Diğer Hazır Değerler', 'Other Cash and Cash Equivalents', 'asset', '10', 3, true),
  ('TR', '12', 'Ticari Alacaklar', 'Trade Receivables', 'asset', '1', 2, true),
  ('TR', '120', 'Alıcılar', 'Trade Debtors', 'asset', '12', 3, true),
  ('TR', '121', 'Alacak Senetleri', 'Notes Receivable', 'asset', '12', 3, true),
  ('TR', '127', 'Diğer Ticari Alacaklar', 'Other Trade Receivables', 'asset', '12', 3, true),
  ('TR', '128', 'Şüpheli Ticari Alacaklar', 'Doubtful Trade Receivables', 'asset', '12', 3, true),
  ('TR', '129', 'Şüpheli Alacaklar Karşılığı (-)', 'Provision for Doubtful Receivables (-)', 'asset', '12', 3, true),
  ('TR', '13', 'Diğer Alacaklar', 'Other Receivables', 'asset', '1', 2, true),
  ('TR', '131', 'Ortaklardan Alacaklar', 'Receivables from Shareholders', 'asset', '13', 3, true),
  ('TR', '132', 'İştiraklerden Alacaklar', 'Receivables from Affiliates', 'asset', '13', 3, true),
  ('TR', '133', 'Bağlı Ortaklıklardan Alacaklar', 'Receivables from Subsidiaries', 'asset', '13', 3, true),
  ('TR', '135', 'Personelden Alacaklar', 'Receivables from Employees', 'asset', '13', 3, true),
  ('TR', '136', 'Diğer Çeşitli Alacaklar', 'Other Miscellaneous Receivables', 'asset', '13', 3, true),
  ('TR', '15', 'Stoklar', 'Inventories', 'asset', '1', 2, true),
  ('TR', '150', 'İlk Madde ve Malzeme', 'Raw Materials and Supplies', 'asset', '15', 3, true),
  ('TR', '151', 'Yarı Mamuller', 'Work in Process', 'asset', '15', 3, true),
  ('TR', '152', 'Mamuller', 'Finished Goods', 'asset', '15', 3, true),
  ('TR', '153', 'Ticari Mallar', 'Merchandise', 'asset', '15', 3, true),
  ('TR', '157', 'Diğer Stoklar', 'Other Inventories', 'asset', '15', 3, true),
  ('TR', '158', 'Stok Değer Düşüklüğü Karşılığı (-)', 'Provision for Inventory Impairment (-)', 'asset', '15', 3, true),
  ('TR', '19', 'Diğer Dönen Varlıklar', 'Other Current Assets', 'asset', '1', 2, true),
  ('TR', '190', 'Devreden KDV', 'Carried Forward VAT', 'asset', '19', 3, true),
  ('TR', '191', 'İndirilecek KDV', 'Deductible VAT', 'asset', '19', 3, true),
  ('TR', '192', 'Diğer KDV', 'Other VAT', 'asset', '19', 3, true),
  ('TR', '195', 'İş Avansları', 'Business Advances', 'asset', '19', 3, true),
  ('TR', '196', 'Personel Avansları', 'Employee Advances', 'asset', '19', 3, true),
  ('TR', '197', 'Sayım ve Tesellüm Noksanları', 'Counting and Receipt Shortages', 'asset', '19', 3, true),
  ('TR', '199', 'Diğer Çeşitli Dönen Varlıklar', 'Other Miscellaneous Current Assets', 'asset', '19', 3, true),
  ('TR', '2', 'Duran Varlıklar', 'Non-Current Assets', 'asset', NULL, 1, true),
  ('TR', '22', 'Ticari Alacaklar', 'Trade Receivables', 'asset', '2', 2, true),
  ('TR', '220', 'Alıcılar', 'Trade Debtors', 'asset', '22', 3, true),
  ('TR', '221', 'Alacak Senetleri', 'Notes Receivable', 'asset', '22', 3, true),
  ('TR', '25', 'Maddi Duran Varlıklar', 'Tangible Fixed Assets', 'asset', '2', 2, true),
  ('TR', '250', 'Arazi ve Arsalar', 'Land and Plots', 'asset', '25', 3, true),
  ('TR', '251', 'Yeraltı ve Yerüstü Düzenleri', 'Underground and Surface Structures', 'asset', '25', 3, true),
  ('TR', '252', 'Binalar', 'Buildings', 'asset', '25', 3, true),
  ('TR', '253', 'Tesis, Makine ve Cihazlar', 'Plant, Machinery and Equipment', 'asset', '25', 3, true),
  ('TR', '254', 'Taşıtlar', 'Vehicles', 'asset', '25', 3, true),
  ('TR', '255', 'Demirbaşlar', 'Furniture and Fixtures', 'asset', '25', 3, true),
  ('TR', '256', 'Diğer Maddi Duran Varlıklar', 'Other Tangible Fixed Assets', 'asset', '25', 3, true),
  ('TR', '257', 'Birikmiş Amortismanlar (-)', 'Accumulated Depreciation (-)', 'asset', '25', 3, true),
  ('TR', '258', 'Yapılmakta Olan Yatırımlar', 'Construction in Progress', 'asset', '25', 3, true),
  ('TR', '259', 'Verilen Avanslar', 'Advances Given', 'asset', '25', 3, true),
  ('TR', '26', 'Maddi Olmayan Duran Varlıklar', 'Intangible Fixed Assets', 'asset', '2', 2, true),
  ('TR', '260', 'Haklar', 'Rights', 'asset', '26', 3, true),
  ('TR', '261', 'Şerefiye', 'Goodwill', 'asset', '26', 3, true),
  ('TR', '262', 'Kuruluş ve Örgütlenme Giderleri', 'Pre-operating and Organizational Expenses', 'asset', '26', 3, true),
  ('TR', '263', 'Araştırma ve Geliştirme Giderleri', 'Research and Development Expenses', 'asset', '26', 3, true),
  ('TR', '264', 'Özel Maliyetler', 'Special Costs', 'asset', '26', 3, true),
  ('TR', '267', 'Diğer Maddi Olmayan Duran Varlıklar', 'Other Intangible Fixed Assets', 'asset', '26', 3, true),
  ('TR', '268', 'Birikmiş Amortismanlar (-)', 'Accumulated Amortization (-)', 'asset', '26', 3, true),
  ('TR', '3', 'Kısa Vadeli Yabancı Kaynaklar', 'Current Liabilities', 'liability', NULL, 1, true),
  ('TR', '30', 'Mali Borçlar', 'Financial Payables', 'liability', '3', 2, true),
  ('TR', '300', 'Banka Kredileri', 'Bank Loans', 'liability', '30', 3, true),
  ('TR', '303', 'Uzun Vadeli Kredilerin Anapara Taksitleri', 'Current Portion of Long-Term Loans', 'liability', '30', 3, true),
  ('TR', '304', 'Tahvil Anapara Borç Taksit ve Faizleri', 'Bond Principal Instalments and Interest', 'liability', '30', 3, true),
  ('TR', '308', 'Menkul Kıymetler İhraç Farkı', 'Securities Issue Premium', 'liability', '30', 3, true),
  ('TR', '32', 'Ticari Borçlar', 'Trade Payables', 'liability', '3', 2, true),
  ('TR', '320', 'Satıcılar', 'Suppliers', 'liability', '32', 3, true),
  ('TR', '321', 'Borç Senetleri', 'Notes Payable', 'liability', '32', 3, true),
  ('TR', '322', 'Borç Senetleri Reeskontu (-)', 'Discount on Notes Payable (-)', 'liability', '32', 3, true),
  ('TR', '326', 'Alınan Depozito ve Teminatlar', 'Deposits and Guarantees Received', 'liability', '32', 3, true),
  ('TR', '329', 'Diğer Ticari Borçlar', 'Other Trade Payables', 'liability', '32', 3, true),
  ('TR', '33', 'Diğer Borçlar', 'Other Payables', 'liability', '3', 2, true),
  ('TR', '331', 'Ortaklara Borçlar', 'Payables to Shareholders', 'liability', '33', 3, true),
  ('TR', '332', 'İştiraklere Borçlar', 'Payables to Affiliates', 'liability', '33', 3, true),
  ('TR', '333', 'Bağlı Ortaklıklara Borçlar', 'Payables to Subsidiaries', 'liability', '33', 3, true),
  ('TR', '335', 'Personele Borçlar', 'Payables to Employees', 'liability', '33', 3, true),
  ('TR', '336', 'Diğer Çeşitli Borçlar', 'Other Miscellaneous Payables', 'liability', '33', 3, true),
  ('TR', '34', 'Alınan Avanslar', 'Advances Received', 'liability', '3', 2, true),
  ('TR', '340', 'Alınan Sipariş Avansları', 'Order Advances Received', 'liability', '34', 3, true),
  ('TR', '349', 'Alınan Diğer Avanslar', 'Other Advances Received', 'liability', '34', 3, true),
  ('TR', '36', 'Ödenecek Vergi ve Diğer Yükümlülükler', 'Taxes and Other Liabilities Payable', 'liability', '3', 2, true),
  ('TR', '360', 'Ödenecek Vergi ve Fonlar', 'Taxes and Funds Payable', 'liability', '36', 3, true),
  ('TR', '361', 'Ödenecek Sosyal Güvenlik Kesintileri', 'Social Security Withholdings Payable', 'liability', '36', 3, true),
  ('TR', '368', 'Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler', 'Overdue, Deferred or Instalment Tax Liabilities', 'liability', '36', 3, true),
  ('TR', '369', 'Ödenecek Diğer Yükümlülükler', 'Other Liabilities Payable', 'liability', '36', 3, true),
  ('TR', '37', 'Borç ve Gider Karşılıkları', 'Provisions for Liabilities and Expenses', 'liability', '3', 2, true),
  ('TR', '370', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', 'Current Period Profit Tax and Legal Liability Provisions', 'liability', '37', 3, true),
  ('TR', '371', 'Dönem Kârının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', 'Prepaid Taxes on Current Period Profit (-)', 'liability', '37', 3, true),
  ('TR', '372', 'Kıdem Tazminatı Karşılığı', 'Severance Pay Provision', 'liability', '37', 3, true),
  ('TR', '373', 'Maliyet Giderleri Karşılığı', 'Cost Expense Provision', 'liability', '37', 3, true),
  ('TR', '39', 'Diğer Kısa Vadeli Yabancı Kaynaklar', 'Other Current Liabilities', 'liability', '3', 2, true),
  ('TR', '391', 'Hesaplanan KDV', 'Output VAT', 'liability', '39', 3, true),
  ('TR', '392', 'Diğer KDV', 'Other VAT', 'liability', '39', 3, true),
  ('TR', '395', 'Merkez ve Şubeler Cari Hesabı', 'Head Office and Branches Current Account', 'liability', '39', 3, true),
  ('TR', '397', 'Sayım ve Tesellüm Fazlaları', 'Counting and Receipt Surpluses', 'liability', '39', 3, true),
  ('TR', '399', 'Diğer Çeşitli Yabancı Kaynaklar', 'Other Miscellaneous Liabilities', 'liability', '39', 3, true),
  ('TR', '4', 'Uzun Vadeli Yabancı Kaynaklar', 'Long-Term Liabilities', 'liability', NULL, 1, true),
  ('TR', '40', 'Mali Borçlar', 'Financial Payables', 'liability', '4', 2, true),
  ('TR', '400', 'Banka Kredileri', 'Bank Loans', 'liability', '40', 3, true),
  ('TR', '405', 'Çıkarılmış Tahviller', 'Issued Bonds', 'liability', '40', 3, true),
  ('TR', '407', 'Çıkarılmış Diğer Menkul Kıymetler', 'Other Issued Securities', 'liability', '40', 3, true),
  ('TR', '408', 'Menkul Kıymetler İhraç Farkı (-)', 'Securities Issue Discount (-)', 'liability', '40', 3, true),
  ('TR', '409', 'Diğer Mali Borçlar', 'Other Financial Payables', 'liability', '40', 3, true),
  ('TR', '42', 'Ticari Borçlar', 'Trade Payables', 'liability', '4', 2, true),
  ('TR', '420', 'Satıcılar', 'Suppliers', 'liability', '42', 3, true),
  ('TR', '421', 'Borç Senetleri', 'Notes Payable', 'liability', '42', 3, true),
  ('TR', '426', 'Alınan Depozito ve Teminatlar', 'Deposits and Guarantees Received', 'liability', '42', 3, true),
  ('TR', '429', 'Diğer Ticari Borçlar', 'Other Trade Payables', 'liability', '42', 3, true),
  ('TR', '5', 'Öz Kaynaklar', 'Equity', 'equity', NULL, 1, true),
  ('TR', '50', 'Ödenmiş Sermaye', 'Paid-in Capital', 'equity', '5', 2, true),
  ('TR', '500', 'Sermaye', 'Capital', 'equity', '50', 3, true),
  ('TR', '501', 'Ödenmemiş Sermaye (-)', 'Unpaid Capital (-)', 'equity', '50', 3, true),
  ('TR', '52', 'Sermaye Yedekleri', 'Capital Reserves', 'equity', '5', 2, true),
  ('TR', '520', 'Hisse Senedi İhraç Primleri', 'Share Premium', 'equity', '52', 3, true),
  ('TR', '521', 'Hisse Senedi İptal Kârları', 'Gains on Share Cancellation', 'equity', '52', 3, true),
  ('TR', '522', 'M.D.V. Yeniden Değerleme Artışları', 'Revaluation Increases on Tangible Fixed Assets', 'equity', '52', 3, true),
  ('TR', '54', 'Kâr Yedekleri', 'Profit Reserves', 'equity', '5', 2, true),
  ('TR', '540', 'Yasal Yedekler', 'Legal Reserves', 'equity', '54', 3, true),
  ('TR', '541', 'Statü Yedekleri', 'Statutory Reserves', 'equity', '54', 3, true),
  ('TR', '542', 'Olağanüstü Yedekler', 'Extraordinary Reserves', 'equity', '54', 3, true),
  ('TR', '57', 'Geçmiş Yıllar Kârları', 'Prior Years Profits', 'equity', '5', 2, true),
  ('TR', '570', 'Geçmiş Yıllar Kârları', 'Prior Years Profits', 'equity', '57', 3, true),
  ('TR', '58', 'Geçmiş Yıllar Zararları', 'Prior Years Losses', 'equity', '5', 2, true),
  ('TR', '580', 'Geçmiş Yıllar Zararları (-)', 'Prior Years Losses (-)', 'equity', '58', 3, true),
  ('TR', '59', 'Dönem Net Kârı (Zararı)', 'Current Period Net Profit (Loss)', 'equity', '5', 2, true),
  ('TR', '590', 'Dönem Net Kârı', 'Current Period Net Profit', 'equity', '59', 3, true),
  ('TR', '591', 'Dönem Net Zararı (-)', 'Current Period Net Loss (-)', 'equity', '59', 3, true),
  ('TR', '6', 'Gelir Tablosu Hesapları', 'Income Statement Accounts', 'revenue', NULL, 1, true),
  ('TR', '60', 'Brüt Satışlar', 'Gross Sales', 'revenue', '6', 2, true),
  ('TR', '600', 'Yurtiçi Satışlar', 'Domestic Sales', 'revenue', '60', 3, true),
  ('TR', '601', 'Yurtdışı Satışlar', 'Export Sales', 'revenue', '60', 3, true),
  ('TR', '602', 'Diğer Gelirler', 'Other Revenues', 'revenue', '60', 3, true),
  ('TR', '61', 'Satış İndirimleri', 'Sales Deductions', 'expense', '6', 2, true),
  ('TR', '610', 'Satıştan İadeler (-)', 'Sales Returns (-)', 'expense', '61', 3, true),
  ('TR', '611', 'Satış İskontoları (-)', 'Sales Discounts (-)', 'expense', '61', 3, true),
  ('TR', '612', 'Diğer İndirimler (-)', 'Other Deductions (-)', 'expense', '61', 3, true),
  ('TR', '62', 'Satışların Maliyeti', 'Cost of Sales', 'expense', '6', 2, true),
  ('TR', '620', 'Satılan Mamuller Maliyeti (-)', 'Cost of Finished Goods Sold (-)', 'expense', '62', 3, true),
  ('TR', '621', 'Satılan Ticari Mallar Maliyeti (-)', 'Cost of Merchandise Sold (-)', 'expense', '62', 3, true),
  ('TR', '622', 'Satılan Hizmet Maliyeti (-)', 'Cost of Services Sold (-)', 'expense', '62', 3, true),
  ('TR', '623', 'Diğer Satışların Maliyeti (-)', 'Cost of Other Sales (-)', 'expense', '62', 3, true),
  ('TR', '63', 'Faaliyet Giderleri', 'Operating Expenses', 'expense', '6', 2, true),
  ('TR', '630', 'Araştırma ve Geliştirme Giderleri (-)', 'Research and Development Expenses (-)', 'expense', '63', 3, true),
  ('TR', '631', 'Pazarlama, Satış ve Dağıtım Giderleri (-)', 'Marketing, Selling and Distribution Expenses (-)', 'expense', '63', 3, true),
  ('TR', '632', 'Genel Yönetim Giderleri (-)', 'General Administrative Expenses (-)', 'expense', '63', 3, true),
  ('TR', '64', 'Diğer Faaliyetlerden Olağan Gelir ve Kârlar', 'Other Ordinary Operating Income and Profits', 'revenue', '6', 2, true),
  ('TR', '640', 'İştiraklerden Temettü Gelirleri', 'Dividend Income from Affiliates', 'revenue', '64', 3, true),
  ('TR', '641', 'Bağlı Ortaklıklardan Temettü Gelirleri', 'Dividend Income from Subsidiaries', 'revenue', '64', 3, true),
  ('TR', '642', 'Faiz Gelirleri', 'Interest Income', 'revenue', '64', 3, true),
  ('TR', '643', 'Komisyon Gelirleri', 'Commission Income', 'revenue', '64', 3, true),
  ('TR', '644', 'Konusu Kalmayan Karşılıklar', 'Reversed Provisions', 'revenue', '64', 3, true),
  ('TR', '645', 'Menkul Kıymet Satış Kârları', 'Gains on Securities Sales', 'revenue', '64', 3, true),
  ('TR', '646', 'Kambiyo Kârları', 'Foreign Exchange Gains', 'revenue', '64', 3, true),
  ('TR', '647', 'Reeskont Faiz Gelirleri', 'Rediscount Interest Income', 'revenue', '64', 3, true),
  ('TR', '649', 'Diğer Olağan Gelir ve Kârlar', 'Other Ordinary Income and Profits', 'revenue', '64', 3, true),
  ('TR', '65', 'Diğer Faaliyetlerden Olağan Gider ve Zararlar', 'Other Ordinary Operating Expenses and Losses', 'expense', '6', 2, true),
  ('TR', '653', 'Komisyon Giderleri (-)', 'Commission Expenses (-)', 'expense', '65', 3, true),
  ('TR', '654', 'Karşılık Giderleri (-)', 'Provision Expenses (-)', 'expense', '65', 3, true),
  ('TR', '655', 'Menkul Kıymet Satış Zararları (-)', 'Losses on Securities Sales (-)', 'expense', '65', 3, true),
  ('TR', '656', 'Kambiyo Zararları (-)', 'Foreign Exchange Losses (-)', 'expense', '65', 3, true),
  ('TR', '657', 'Reeskont Faiz Giderleri (-)', 'Rediscount Interest Expenses (-)', 'expense', '65', 3, true),
  ('TR', '659', 'Diğer Olağan Gider ve Zararlar (-)', 'Other Ordinary Expenses and Losses (-)', 'expense', '65', 3, true),
  ('TR', '66', 'Finansman Giderleri', 'Financing Expenses', 'expense', '6', 2, true),
  ('TR', '660', 'Kısa Vadeli Borçlanma Giderleri (-)', 'Short-Term Borrowing Expenses (-)', 'expense', '66', 3, true),
  ('TR', '661', 'Uzun Vadeli Borçlanma Giderleri (-)', 'Long-Term Borrowing Expenses (-)', 'expense', '66', 3, true),
  ('TR', '67', 'Olağandışı Gelir ve Kârlar', 'Extraordinary Income and Profits', 'revenue', '6', 2, true),
  ('TR', '671', 'Önceki Dönem Gelir ve Kârları', 'Prior Period Income and Profits', 'revenue', '67', 3, true),
  ('TR', '679', 'Diğer Olağandışı Gelir ve Kârlar', 'Other Extraordinary Income and Profits', 'revenue', '67', 3, true),
  ('TR', '68', 'Olağandışı Gider ve Zararlar', 'Extraordinary Expenses and Losses', 'expense', '6', 2, true),
  ('TR', '680', 'Çalışmayan Kısım Gider ve Zararları (-)', 'Idle Capacity Expenses and Losses (-)', 'expense', '68', 3, true),
  ('TR', '681', 'Önceki Dönem Gider ve Zararları (-)', 'Prior Period Expenses and Losses (-)', 'expense', '68', 3, true),
  ('TR', '689', 'Diğer Olağandışı Gider ve Zararlar (-)', 'Other Extraordinary Expenses and Losses (-)', 'expense', '68', 3, true),
  ('TR', '69', 'Dönem Net Kâr veya Zararı', 'Current Period Net Profit or Loss', 'equity', '6', 2, true),
  ('TR', '690', 'Dönem Kârı veya Zararı', 'Period Profit or Loss', 'equity', '69', 3, true),
  ('TR', '691', 'Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', 'Period Profit Tax and Legal Liability Provisions (-)', 'equity', '69', 3, true),
  ('TR', '692', 'Dönem Net Kârı veya Zararı', 'Current Period Net Profit or Loss', 'equity', '69', 3, true),
  ('TR', '7', 'Maliyet Hesapları', 'Cost Accounts', 'cost', NULL, 1, true),
  ('TR', '71', 'Direkt İlk Madde ve Malzeme Giderleri', 'Direct Raw Material and Supplies Expenses', 'cost', '7', 2, true),
  ('TR', '710', 'Direkt İlk Madde ve Malzeme Giderleri', 'Direct Raw Material and Supplies Expenses', 'cost', '71', 3, true),
  ('TR', '711', 'Direkt İlk Madde ve Malzeme Yansıtma Hesabı', 'Direct Raw Material and Supplies Allocation Account', 'cost', '71', 3, true),
  ('TR', '712', 'Direkt İlk Madde ve Malzeme Fiyat Farkı', 'Direct Raw Material Price Variance', 'cost', '71', 3, true),
  ('TR', '713', 'Direkt İlk Madde ve Malzeme Miktar Farkı', 'Direct Raw Material Quantity Variance', 'cost', '71', 3, true),
  ('TR', '72', 'Direkt İşçilik Giderleri', 'Direct Labor Expenses', 'cost', '7', 2, true),
  ('TR', '720', 'Direkt İşçilik Giderleri', 'Direct Labor Expenses', 'cost', '72', 3, true),
  ('TR', '721', 'Direkt İşçilik Giderleri Yansıtma Hesabı', 'Direct Labor Allocation Account', 'cost', '72', 3, true),
  ('TR', '722', 'Direkt İşçilik Ücret Farkları', 'Direct Labor Rate Variance', 'cost', '72', 3, true),
  ('TR', '723', 'Direkt İşçilik Süre (Zaman) Farkları', 'Direct Labor Time Variance', 'cost', '72', 3, true),
  ('TR', '73', 'Genel Üretim Giderleri', 'Manufacturing Overhead', 'cost', '7', 2, true),
  ('TR', '730', 'Genel Üretim Giderleri', 'Manufacturing Overhead', 'cost', '73', 3, true),
  ('TR', '731', 'Genel Üretim Giderleri Yansıtma Hesabı', 'Manufacturing Overhead Allocation Account', 'cost', '73', 3, true),
  ('TR', '732', 'Genel Üretim Giderleri Bütçe Farkları', 'Manufacturing Overhead Budget Variance', 'cost', '73', 3, true),
  ('TR', '733', 'Genel Üretim Giderleri Verimlilik Farkları', 'Manufacturing Overhead Efficiency Variance', 'cost', '73', 3, true),
  ('TR', '734', 'Genel Üretim Giderleri Kapasite Farkları', 'Manufacturing Overhead Capacity Variance', 'cost', '73', 3, true),
  ('TR', '74', 'Hizmet Üretim Maliyeti', 'Service Production Cost', 'cost', '7', 2, true),
  ('TR', '740', 'Hizmet Üretim Maliyeti', 'Service Production Cost', 'cost', '74', 3, true),
  ('TR', '741', 'Hizmet Üretim Maliyeti Yansıtma Hesabı', 'Service Production Cost Allocation Account', 'cost', '74', 3, true),
  ('TR', '742', 'Hizmet Üretim Maliyeti Fark Hesapları', 'Service Production Cost Variance Accounts', 'cost', '74', 3, true),
  ('TR', '75', 'Araştırma ve Geliştirme Giderleri', 'Research and Development Expenses', 'cost', '7', 2, true),
  ('TR', '750', 'Araştırma ve Geliştirme Giderleri', 'Research and Development Expenses', 'cost', '75', 3, true),
  ('TR', '751', 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı', 'R&D Allocation Account', 'cost', '75', 3, true),
  ('TR', '752', 'Araştırma ve Geliştirme Gider Farkları', 'R&D Expense Variances', 'cost', '75', 3, true),
  ('TR', '76', 'Pazarlama Satış ve Dağıtım Giderleri', 'Marketing, Selling and Distribution Expenses', 'cost', '7', 2, true),
  ('TR', '760', 'Pazarlama Satış ve Dağıtım Giderleri', 'Marketing, Selling and Distribution Expenses', 'cost', '76', 3, true),
  ('TR', '761', 'Pazarlama Satış ve Dağıtım Giderleri Yansıtma Hesabı', 'Marketing, Selling and Distribution Allocation Account', 'cost', '76', 3, true),
  ('TR', '762', 'Pazarlama Satış ve Dağıtım Giderleri Fark Hesabı', 'Marketing, Selling and Distribution Variance Account', 'cost', '76', 3, true),
  ('TR', '77', 'Genel Yönetim Giderleri', 'General Administrative Expenses', 'cost', '7', 2, true),
  ('TR', '770', 'Genel Yönetim Giderleri', 'General Administrative Expenses', 'cost', '77', 3, true),
  ('TR', '771', 'Genel Yönetim Giderleri Yansıtma Hesabı', 'General Administrative Allocation Account', 'cost', '77', 3, true),
  ('TR', '772', 'Genel Yönetim Gider Farkları', 'General Administrative Expense Variances', 'cost', '77', 3, true),
  ('TR', '78', 'Finansman Giderleri', 'Financing Expenses', 'cost', '7', 2, true),
  ('TR', '780', 'Finansman Giderleri', 'Financing Expenses', 'cost', '78', 3, true),
  ('TR', '781', 'Finansman Giderleri Yansıtma Hesabı', 'Financing Expenses Allocation Account', 'cost', '78', 3, true),
  ('TR', '782', 'Finansman Giderleri Fark Hesabı', 'Financing Expenses Variance Account', 'cost', '78', 3, true);

INSERT INTO migrations_log (file_name, notes)
VALUES ('069_turkey_coa_template_rebuild.sql',
  'TR template: resmi Türkiye TDHP 211 hesap (official codes + EN translations).')
ON CONFLICT (file_name) DO NOTHING;

COMMIT;
